# TCL File Generated by Component Editor 12.1
# Tue Nov 27 10:41:54 GMT 2012
# DO NOT MODIFY


# 
# PixelDuplicator "PixelDuplicator" v1.0
# Simon Moore 2012.11.27.10:41:54
# Duplicate an Avalon Stream of pixels to two Avalon Streams
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module PixelDuplicator
# 
set_module_property DESCRIPTION "Duplicate an Avalon Stream of pixels to two Avalon Streams"
set_module_property NAME PixelDuplicator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_Video
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME PixelDuplicator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkPixelDuplicator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkPixelDuplicator.v VERILOG PATH mkPixelDuplicator.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point stream_in
# 
add_interface stream_in avalon_streaming end
set_interface_property stream_in associatedClock clockreset
set_interface_property stream_in associatedReset clockreset_reset
set_interface_property stream_in dataBitsPerSymbol 8
set_interface_property stream_in errorDescriptor ""
set_interface_property stream_in firstSymbolInHighOrderBits true
set_interface_property stream_in maxChannel 0
set_interface_property stream_in readyLatency 0
set_interface_property stream_in ENABLED true

add_interface_port stream_in asi_stream_in_data data Input 24
add_interface_port stream_in asi_stream_in_valid valid Input 1
add_interface_port stream_in asi_stream_in_startofpacket startofpacket Input 1
add_interface_port stream_in asi_stream_in_endofpacket endofpacket Input 1
add_interface_port stream_in asi_stream_in_ready ready Output 1


# 
# connection point a_stream_out
# 
add_interface a_stream_out avalon_streaming start
set_interface_property a_stream_out associatedClock clockreset
set_interface_property a_stream_out associatedReset clockreset_reset
set_interface_property a_stream_out dataBitsPerSymbol 8
set_interface_property a_stream_out errorDescriptor ""
set_interface_property a_stream_out firstSymbolInHighOrderBits true
set_interface_property a_stream_out maxChannel 0
set_interface_property a_stream_out readyLatency 0
set_interface_property a_stream_out ENABLED true

add_interface_port a_stream_out aso_a_stream_out_data data Output 24
add_interface_port a_stream_out aso_a_stream_out_valid valid Output 1
add_interface_port a_stream_out aso_a_stream_out_ready ready Input 1
add_interface_port a_stream_out aso_a_stream_out_startofpacket startofpacket Output 1
add_interface_port a_stream_out aso_a_stream_out_endofpacket endofpacket Output 1


# 
# connection point b_stream_out
# 
add_interface b_stream_out avalon_streaming start
set_interface_property b_stream_out associatedClock clockreset
set_interface_property b_stream_out associatedReset clockreset_reset
set_interface_property b_stream_out dataBitsPerSymbol 8
set_interface_property b_stream_out errorDescriptor ""
set_interface_property b_stream_out firstSymbolInHighOrderBits true
set_interface_property b_stream_out maxChannel 0
set_interface_property b_stream_out readyLatency 0
set_interface_property b_stream_out ENABLED true

add_interface_port b_stream_out aso_b_stream_out_data data Output 24
add_interface_port b_stream_out aso_b_stream_out_valid valid Output 1
add_interface_port b_stream_out aso_b_stream_out_ready ready Input 1
add_interface_port b_stream_out aso_b_stream_out_startofpacket startofpacket Output 1
add_interface_port b_stream_out aso_b_stream_out_endofpacket endofpacket Output 1

