# TCL File Generated by Component Editor 12.1
# Fri Feb 22 12:44:00 GMT 2013
# DO NOT MODIFY


# 
# MTL_Framebuffer_Flash "MTL_Framebuffer_Flash" v1.0
# Simon Moore 2013.02.22.12:44:00
# MTL LCD frame buffer in SSRAM with Flash memory support
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module MTL_Framebuffer_Flash
# 
set_module_property DESCRIPTION "MTL LCD frame buffer in SSRAM with Flash memory support"
set_module_property NAME MTL_Framebuffer_Flash
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_Video
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME MTL_Framebuffer_Flash
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL mkMTL_Framebuffer_Flash
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkMTL_Framebuffer_Flash.v VERILOG PATH mkMTL_Framebuffer_Flash.v
add_fileset_file VerilogAlteraROM.v VERILOG PATH VerilogAlteraROM.v
add_fileset_file vgafontrom.mif MIF PATH vgafontrom.mif


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clockreset
set_interface_property s0 associatedReset clockreset_reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true

add_interface_port s0 avs_s0_address address Input 25
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_byteenable byteenable Input 4
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point stream_out
# 
add_interface stream_out avalon_streaming start
set_interface_property stream_out associatedClock clockreset
set_interface_property stream_out associatedReset clockreset_reset
set_interface_property stream_out dataBitsPerSymbol 24
set_interface_property stream_out errorDescriptor ""
set_interface_property stream_out firstSymbolInHighOrderBits true
set_interface_property stream_out maxChannel 0
set_interface_property stream_out readyLatency 0
set_interface_property stream_out ENABLED true

add_interface_port stream_out aso_stream_out_data data Output 24
add_interface_port stream_out aso_stream_out_valid valid Output 1
add_interface_port stream_out aso_stream_out_ready ready Input 1
add_interface_port stream_out aso_stream_out_startofpacket startofpacket Output 1
add_interface_port stream_out aso_stream_out_endofpacket endofpacket Output 1


# 
# connection point conduit_end_touch
# 
add_interface conduit_end_touch conduit end
set_interface_property conduit_end_touch associatedClock ""
set_interface_property conduit_end_touch associatedReset ""
set_interface_property conduit_end_touch ENABLED true

add_interface_port conduit_end_touch coe_touch_x1 export Input 10
add_interface_port conduit_end_touch coe_touch_y1 export Input 9
add_interface_port conduit_end_touch coe_touch_x2 export Input 10
add_interface_port conduit_end_touch coe_touch_y2 export Input 9
add_interface_port conduit_end_touch coe_touch_count_gesture export Input 10
add_interface_port conduit_end_touch coe_touch_touch_valid export Input 1


# 
# connection point conduit_end_mem
# 
add_interface conduit_end_mem conduit end
set_interface_property conduit_end_mem associatedClock ""
set_interface_property conduit_end_mem associatedReset ""
set_interface_property conduit_end_mem ENABLED true

add_interface_port conduit_end_mem coe_ssram_adv export Output 1
add_interface_port conduit_end_mem coe_ssram_bwa_n export Output 1
add_interface_port conduit_end_mem coe_ssram_bwb_n export Output 1
add_interface_port conduit_end_mem coe_ssram_ce_n export Output 1
add_interface_port conduit_end_mem coe_ssram_cke_n export Output 1
add_interface_port conduit_end_mem coe_ssram_oe_n export Output 1
add_interface_port conduit_end_mem coe_ssram_we_n export Output 1
add_interface_port conduit_end_mem coe_fsm_a export Output 25
add_interface_port conduit_end_mem coe_fsm_d_out export Output 16
add_interface_port conduit_end_mem coe_fsm_d_in export Input 16
add_interface_port conduit_end_mem coe_fsm_dout_req export Output 1
add_interface_port conduit_end_mem coe_flash_adv_n export Output 1
add_interface_port conduit_end_mem coe_flash_ce_n export Output 1
add_interface_port conduit_end_mem coe_flash_clk export Output 1
add_interface_port conduit_end_mem coe_flash_oe_n export Output 1
add_interface_port conduit_end_mem coe_flash_we_n export Output 1

# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint s0
set_interface_property interrupt_sender associatedClock clockreset
set_interface_property interrupt_sender associatedReset clockreset_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender coe_touch_irq irq Output 1

